# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  use_frameworks!
  pod 'CircleOfFifths', :path => '../'
end

target 'Mac' do
  use_frameworks!
  pod 'CircleOfFifths', :path => '../'
end
